# Promtail configuration for Engram log collection
# Collects logs from Engram containers and forwards to Loki

server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Only collect logs from Engram containers
      - source_labels: [__meta_docker_container_name]
        regex: '/(engram|engram-.*)'
        action: keep
      # Extract container name as label
      - source_labels: [__meta_docker_container_name]
        target_label: container
        regex: '/(.*)'
      # Extract container ID
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
        regex: '(.*)'
    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            target: target
            message: message
            memory_space: memory_space
            operation: operation
            duration_ms: duration_ms
      # Extract timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      # Add labels
      - labels:
          level:
          target:
          memory_space:
          operation:

  # Kubernetes pod logs
  - job_name: kubernetes-pods
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      # Only collect logs from Engram pods
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: engram
        action: keep
      # Add pod metadata as labels
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_container_name]
        target_label: container
    pipeline_stages:
      # Parse JSON logs
      - json:
          expressions:
            timestamp: timestamp
            level: level
            target: target
            message: message
            memory_space: memory_space
            operation: operation
            duration_ms: duration_ms
      # Extract timestamp
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      # Add labels
      - labels:
          level:
          target:
          memory_space:
          operation:

  # Local filesystem logs (for testing)
  - job_name: local-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: engram
          __path__: /var/log/engram/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            target: target
            message: message
            memory_space: memory_space
            operation: operation
            duration_ms: duration_ms
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          target:
          memory_space:
          operation:
