apiVersion: v1
kind: ConfigMap
metadata:
  name: engram-config
data:
  engram.toml: |
    [feature_flags]
    spreading_api_beta = true

    [memory_spaces]
    default_space = "default"
    bootstrap_spaces = ["default"]

    [persistence]
    data_root = "/data"
    hot_capacity = 10000
    warm_capacity = 100000
    cold_capacity = 1000000
    flush_interval_sec = 30
    compression_enabled = true

    [consolidation]
    enabled = true
    interval_sec = 60
    batch_size = 1000
    parallel_workers = 4

    [cache]
    size_mb = 2048
    ttl_sec = 3600

    [performance]
    max_concurrent_queries = 100
    query_timeout_sec = 30
