# Headless service for StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{ include "engram.fullname" . }}-headless
  labels:
    {{- include "engram.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "engram.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
  - name: grpc
    port: {{ .Values.service.grpcPort }}

---
# Regular service for client access
apiVersion: v1
kind: Service
metadata:
  name: {{ include "engram.fullname" . }}
  labels:
    {{- include "engram.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "engram.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: http
    protocol: TCP
  - name: grpc
    port: {{ .Values.service.grpcPort }}
    targetPort: grpc
    protocol: TCP
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: {{ .Values.service.sessionAffinityTimeoutSeconds }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
