name = "Multi-Tenant Workload"
description = "Multiple memory spaces concurrently - tenant isolation validation"

[duration]
total_seconds = 3600

[arrival]
pattern = "constant"
rate = 8000.0

[operations]
store_weight = 40.0
recall_weight = 45.0
embedding_search_weight = 15.0
pattern_completion_weight = 0.0

[data]
num_nodes = 500_000
embedding_dim = 768
memory_spaces = 16

[data.embedding_distribution]
type = "clustered"
num_clusters = 10
std_dev = 0.1

[validation]
expected_p99_latency_ms = 12.0
expected_throughput_ops_sec = 8000.0
max_error_rate = 0.001

[chaos]
enabled = false
